# Docker Compose for YouTube Video Processor
version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STORAGE_PATH=/app/data
      - TEMP_PATH=/app/tmp
      - WHISPER_MODEL_PATH=/app/models
      - CLEANUP_INTERVAL_HOURS=24
      - DOWNLOAD_CONCURRENCY=3
      - TRANSCRIPTION_CONCURRENCY=2
      - MAX_FILE_SIZE_MB=1000
      - MAX_DURATION_HOURS=4
    volumes:
      - ./data:/app/data
      - ./tmp:/app/tmp
      - ./models:/app/models
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge